# Generated by Django 3.2.18 on 2023-05-26 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_grade_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='backend.group'),
            preserve_default=False,
        ),
    ]
