# Generated by Django 3.2.18 on 2023-06-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20230601_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
