# Generated by Django 3.2.18 on 2023-05-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_user_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='title',
            new_name='level',
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='Concorde', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('level', 'name', 'year')},
        ),
    ]
