# Generated by Django 3.2.18 on 2023-05-07 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20230507_1534'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmodule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='groupmodule',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmodule',
            name='module',
        ),
        migrations.AlterUniqueTogether(
            name='modulecourse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='modulecourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='modulecourse',
            name='module',
        ),
        migrations.AddField(
            model_name='course',
            name='modules',
            field=models.ManyToManyField(to='backend.Module'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(limit_choices_to={'role': 'TE'}, related_name='teachers', to='backend.User'),
        ),
        migrations.AddField(
            model_name='module',
            name='groups',
            field=models.ManyToManyField(to='backend.Group'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lead_teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'TE'}, on_delete=django.db.models.deletion.PROTECT, related_name='lead_teacher', to='backend.user'),
        ),
        migrations.DeleteModel(
            name='CourseTeacher',
        ),
        migrations.DeleteModel(
            name='GroupModule',
        ),
        migrations.DeleteModel(
            name='ModuleCourse',
        ),
    ]
