# Generated by Django 3.2.18 on 2023-05-07 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20230507_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='referent',
            new_name='referent_id',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='group',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='group',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='usersemester',
            old_name='semester',
            new_name='semester_id',
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('number', 'group_id')},
        ),
        migrations.AlterUniqueTogether(
            name='usersemester',
            unique_together={('user', 'semester_id')},
        ),
    ]
