# Generated by Django 3.2.18 on 2023-05-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20230507_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='referent_id',
            new_name='referent',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='usersemester',
            old_name='semester_id',
            new_name='semester',
        ),
        migrations.AlterField(
            model_name='module',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='backend.Group'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('number', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='usersemester',
            unique_together={('user', 'semester')},
        ),
    ]
