# Generated by Django 3.2.18 on 2023-05-07 22:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20230507_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teachers',
        ),
        migrations.AddField(
            model_name='course',
            name='others_teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'TE'}, null=True, related_name='teachers', to='backend.User'),
        ),
        migrations.AddField(
            model_name='semester',
            name='date_tc',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='modules',
            field=models.ManyToManyField(blank=True, null=True, to='backend.Module'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='number',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='group',
            name='referent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'AR'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referent', to='backend.user'),
        ),
        migrations.AlterField(
            model_name='usersemester',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
