# Generated by Django 3.2.18 on 2023-05-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20230508_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='others_teachers',
            new_name='other_teachers',
        ),
    ]
