# Generated by Django 3.2.18 on 2023-05-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_course_other_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='exam_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
