# Generated by Django 3.2.18 on 2023-05-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_grade_exam_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='other_teachers',
            field=models.ManyToManyField(default=[], limit_choices_to={'role': 'TE'}, related_name='teachers', to='backend.User'),
        ),
        migrations.AlterField(
            model_name='module',
            name='courses',
            field=models.ManyToManyField(blank=True, to='backend.Course'),
        ),
        migrations.AlterField(
            model_name='module',
            name='groups',
            field=models.ManyToManyField(blank=True, to='backend.Group'),
        ),
    ]
